--- #YAML:1.0
name:                Enbugger
version:             0.02
abstract:            Turns the debugger on at runtime.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Josh ben jore <jjore@cpan.org>
