# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Enbugger
version:      1.03
version_from: lib/Enbugger.pm
installdirs:  site
requires:
    B::Utils:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
